server:
  port: 9005
spring:
  application:
    name: gateway
  boot:
    admin:
      client:
        url: http://127.0.0.1:9010
        username: root
        password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 使用 Sentinel 作为熔断器
#    sentinel:
#      transport:
#        port: 9004
#        dashboard: localhost:9003
    zipkin:
      base-url: http://127.0.0.1:9009  #zipkin服务端的地址
    sleuth:
      sampler:
      probability: 1.0 #采样比例，设置为1.0时代表全部强求都需要采样
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      default-filters:
        - name: StripPrefix
          args:
            parts: 1
        - name: Hystrix
          args:
            name: default-gateway-fallback
            fallbackUri: forward:/fallback
      routes:
        # 路由id，建议配合服务名
        - id: order-service
          #匹配路由名
          uri: lb://order-service
          predicates:
            # 断言，路径相匹配的进行路由
            - Path=/order-service/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
        - id: goods-service
          uri: lb://goods-service
          predicates:
            - Path=/goods-service/**
logging:
  config: classpath:logback.xml
ribbon:
  # 开启手动注入，否则会导致第一次调用会失败
  eager-load:
    enabled: true
    clients: order-server,user-server,goods-server